repos:
  # Use local tools to avoid heavy downloads
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: uv run isort --profile black
        language: system
        types: [python]

  # Lightweight pre-commit hooks (no heavy dependencies)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast           # Check Python AST
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

# Configuration
default_stages: [pre-commit]
fail_fast: false
