[project]
name = "personal-knowledgebase-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "pillow>=11.2.1",
    "python-dotenv>=1.1.0",
    "torch==2.7.1",
    "transformers==4.50.0",
]

[dependency-groups]
dev = [
    "huggingface-hub[cli]>=0.32.4",
]
