name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --group test

      - name: Run tests
        run: |
          uv run pytest test_app.py -v

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Check code formatting with black
        run: |
          uv run black --check --diff .

      - name: Check import sorting with isort
        run: |
          uv run isort --check-only --diff .

      - name: Type check with mypy (optional, may fail)
        run: |
          uv run mypy . --ignore-missing-imports || echo "Type checking failed but continuing..."
        continue-on-error: true
